name: Environment Check

on:
  workflow_dispatch:
  push:
    branches: [ feature/cicd-nomad-setup, feature/enhanced-github-actions ]

jobs:
  check-environment:
    name: Check Runner Environment
    runs-on: [self-hosted, linux]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check uv installation
      run: |
        echo "=== UV Installation Check ==="
        uv --version || echo "❌ uv not found in PATH"
        which uv || echo "❌ uv binary not found"
        
        # Try common installation paths
        if [ -f "/home/diva/.local/bin/uv" ]; then
          echo "✅ Found uv at /home/diva/.local/bin/uv"
          /home/diva/.local/bin/uv --version
        fi
        
    - name: Set up uv if needed
      run: |
        if ! command -v uv &> /dev/null; then
          echo "Installing uv..."
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        fi
        
    - name: Validate uv functionality
      run: |
        echo "=== UV Functionality Test ==="
        uv --version
        uv python list        
    - name: Check Python versions
      run: |
        echo "=== Python Version Check ==="
        python3 --version
        python3 -c "import sys; print(f'Python {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}')"
        which python3
        
        # Check for multiple Python versions
        for version in 3.11 3.12; do
          if command -v python$version &> /dev/null; then
            echo "✅ Python $version available: $(python$version --version)"
          else
            echo "⚠️  Python $version not available"
          fi
        done
        
    - name: Test uv project setup
      run: |
        echo "=== UV Project Setup Test ==="
        if [ -f "uv.lock" ]; then
          echo "✅ uv.lock file found"
          uv sync --dry-run || echo "⚠️  uv sync failed (dry-run)"
        else
          echo "❌ uv.lock file not found"
        fi
        
        if [ -f "pyproject.toml" ]; then
          echo "✅ pyproject.toml found"
        else
          echo "❌ pyproject.toml not found"
        fi
        
    - name: Test workflow tools
      run: |
        echo "=== Workflow Tools Check ==="
        
        # Check Docker
        docker --version || echo "⚠️  Docker not available"
        docker info | head -5 || echo "⚠️  Docker info failed"
        
        # Check Nomad connectivity
        curl -s http://192.168.0.174:4646/v1/status/leader || echo "⚠️  Nomad not reachable"
        
        # Check GitHub CLI if available
        gh --version || echo "⚠️  GitHub CLI not available"
        
    - name: System info
      run: |
        echo "=== System Information ==="
        echo "OS: $(lsb_release -d | cut -f2)"
        echo "Kernel: $(uname -r)"
        echo "Architecture: $(uname -m)"
        echo "CPU cores: $(nproc)"
        echo "Memory: $(free -h | grep '^Mem:' | awk '{print $2}')"
        echo "Disk space: $(df -h / | tail -1 | awk '{print $4}' || echo 'unknown')"        
    - name: Check Python versions
      run: |
        echo "=== Python Version Check ==="
        python3 --version
        python3 -c "import sys; print(f'Python {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}')"
        which python3
        
        # Check for multiple Python versions
        for version in 3.11 3.12; do
          if command -v python$version &> /dev/null; then
            echo "✅ Python $version available: $(python$version --version)"
          else
            echo "⚠️  Python $version not available"
          fi
        done
        
    - name: Test uv project setup
      run: |
        echo "=== UV Project Setup Test ==="
        if [ -f "uv.lock" ]; then
          echo "✅ uv.lock file found"
          uv sync --dry-run || echo "⚠️  uv sync failed (dry-run)"
        else
          echo "❌ uv.lock file not found"
        fi
        
        if [ -f "pyproject.toml" ]; then
          echo "✅ pyproject.toml found"
        else
          echo "❌ pyproject.toml not found"
        fi        
    - name: Test workflow tools
      run: |
        echo "=== Workflow Tools Check ==="
        
        # Check Docker
        docker --version || echo "⚠️  Docker not available"
        docker info | head -5 || echo "⚠️  Docker info failed"
        
        # Check Nomad connectivity
        curl -s http://192.168.0.174:4646/v1/status/leader || echo "⚠️  Nomad not reachable"
        
        # Check GitHub CLI if available
        gh --version || echo "⚠️  GitHub CLI not available"
        
    - name: System info
      run: |
        echo "=== System Information ==="
        echo "OS: $(lsb_release -d | cut -f2)"
        echo "Kernel: $(uname -r)"
        echo "Architecture: $(uname -m)"
        echo "CPU cores: $(nproc)"
        echo "Memory: $(free -h | grep '^Mem:' | awk '{print $2}')"
        echo "Disk space: $(df -h / | tail -1 | awk '{print $4}' || echo 'unknown')"